---
- hosts: all
  become: true
  become_user: root

  tasks:
    # Run Insight on local server
    - name: Run Insight on local server
      ansible.builtin.command: /usr/bin/insights-client
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
