---
- name: Register Insights for local server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Register Insights for local server
      ansible.builtin.command: /usr/bin/insights-client --register
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
