---
- name: Insight check in for local server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Insight check in for local server
      ansible.builtin.command:
        cmd: /usr/bin/insights-client --checkin
      register: insight_client_checkin
      changed_when: false
      failed_when: "'FAILED' in insight_client_checkin.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
