---
- name: Update compliance for local server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Update compliance for local server
      ansible.builtin.command: /usr/bin/insights-client --compliance
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
