---
- name: Run Insight on local server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Run Insight on local server
      ansible.builtin.command:
        cmd: /usr/bin/insights-client --collector malware-detection
      register: insight_client_malware
      changed_when: false
      failed_when: "'FAILED' in insight_client_malware.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
