---
- hosts: all
  become: true
  become_user: root

  tasks:
    # Insight check in for local server
    - name: Insight check in for local server
      ansible.builtin.command: /usr/bin/insights-client --checkin
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
