---
- name: Update compliance for local server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Update compliance for local server
      ansible.builtin.command:
        cmd: /usr/bin/insights-client --compliance
      register: insight_client_compliance
      changed_when: false
      failed_when: "'FAILED' in insight_client_compliance.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
