---
- name: Check RedHat connector status
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Check status of local server with Red Hat
      ansible.builtin.command:
        cmd: /usr/bin/rhc status
      register: rhc_status
      changed_when: false
      failed_when: "'FAILED' in rhc_status.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
