---
- name: Register RedHat connector
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Deploy rhc packages
      ansible.builtin.dnf:
        name:
          - rhc
          - rhc-worker-playbook
        state: present

    - name: Register local server with Red Hat
      ansible.builtin.command:
        cmd: /usr/bin/rhc connect -a {{ rhn_activation_key }} -o {{ rhn_organization_id }}
      register: rhc_connect
      changed_when: false
      failed_when: "'FAILED' in rhc_connect.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8

    - name: Check status of local server with Red Hat
      ansible.builtin.command:
        cmd: /usr/bin/rhc status
      register: rhc_status
      changed_when: false
      failed_when: "'FAILED' in rhc_status.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
