---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: Deploy rhc packages
      ansible.builtin.dnf:
        name:
          - rhc
          - rhc-worker-playbook
        state: present

    - name: Register local server with Red Hat
      ansible.builtin.command: /usr/bin/rhc connect -u {{ rhn_user }} -p {{ rhn_password }}
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int == 8

    - name: Check status of local server with Red Hat
      ansible.builtin.command: /usr/bin/rhc status
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int == 8
