---
- name: Register local sevrer at RedHat network
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Register local server with RHN (Premium)
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        syspurpose:
          usage: "Production"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Premium"
          sync: true
        auto_attach: true
      when:
        - rhn_activation_key == "Premium-RHEL"
        - ansible_facts['os_family'] == "RedHat"

    - name: Register local server with RHN (Standard)
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        syspurpose:
          usage: "Development/Test"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Standard"
          sync: true
        auto_attach: true
      when:
        - rhn_activation_key == "Standard-RHEL"
        - ansible_facts['os_family'] == "RedHat"

    - name: Register local server with RHN (Development)
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        syspurpose:
          usage: "Development/Test"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Self-Support"
          sync: true
        auto_attach: true
      when:
        - rhn_activation_key == "Developer-RHEL"
        - ansible_facts['os_family'] == "RedHat"
