---
- name: Register local sevrer at RedHat network
  hosts: all
  become: true
  become_user: root
  vars:
    rhn_activation_key: "unset"
    rhn_organization_id: "unset"
    rhn_pool_id: "unset"

  tasks:
    - name: Register in RHN with RHEL development subscription
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        pool_ids: "{{ rhn_pool_id }}"
        syspurpose:
          usage: "Development/Test"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Self-Support"
          sync: true
      when:
        - rhn_activation_key == "Developer-RHEL"
        - ansible_facts['os_family'] == "RedHat"

    - name: Register in RHN with RHEL standard subscription
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        pool_ids: "{{ rhn_pool_id }}"
        syspurpose:
          usage: "Production"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Standard"
          sync: true
      when:
        - rhn_activation_key == "Standard-RHEL"
        - ansible_facts['os_family'] == "RedHat"

    - name: Register in RHN with RHEL SAP standard subscription
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        pool_ids: "{{ rhn_pool_id }}"
        syspurpose:
          usage: "Development/Test"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Standard"
          sync: true
      when:
        - rhn_activation_key == "Standard-SAP-RHEL"
        - ansible_facts['os_family'] == "RedHat"

    - name: Register in RHN with RHEL SAP premium subscription
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        pool_ids: "{{ rhn_pool_id }}"
        syspurpose:
          usage: "Production"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Premium"
          sync: true
      when:
        - rhn_activation_key == "Premium-SAP-RHEL"
        - ansible_facts['os_family'] == "RedHat"
