---
- name: Register local sevrer at RedHat network
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Register local server with RHN
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rhn_activation_key }}"
        org_id: "{{ rhn_organization_id }}"
        auto_attach: true
        syspurpose:
          usage: "Development/Test"
          role: "Red Hat Enterprise Linux Server"
          service_level_agreement: "Standard"
          sync: true
      when:
        - ansible_facts['os_family'] == "RedHat"
