---
- name: Refresh subscription for local server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Refresh RHEL subscription
      ansible.builtin.command:
        cmd: /usr/sbin/subscription-manager refresh
      register: subscription_manager_refresh
      changed_when: false
      failed_when: "'FAILED' in subscription_manager_refresh.stderr"
      when:
        - ansible_facts['os_family'] == "RedHat"
