---
- hosts: all
  become: true
  become_user: root

  tasks:
    # Upgrade local server
    - name: Full upgrade for RHEL and clones
      ansible.builtin.dnf:
        update_cache: true
        skip_broken: true
        nobest: true
        name: "*"
        state: latest
        exclude: kernel*
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version']|int >= 8
